{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "74bd293b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "from tkinter import *\n",
    "from PIL import Image, ImageTk\n",
    "import numpy as np\n",
    "from keras.models import load_model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "0ce11cd0",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = load_model(r'models/traffic_classifier_v2.h5')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "b5150a2f",
   "metadata": {},
   "outputs": [],
   "source": [
    "classes = { 1:'Speed limit (20km/h)',\n",
    "            2:'Speed limit (30km/h)', \n",
    "            3:'Speed limit (50km/h)', \n",
    "            4:'Speed limit (60km/h)', \n",
    "            5:'Speed limit (70km/h)', \n",
    "            6:'Speed limit (80km/h)', \n",
    "            7:'End of speed limit (80km/h)', \n",
    "            8:'Speed limit (100km/h)', \n",
    "            9:'Speed limit (120km/h)', \n",
    "            10:'No passing', \n",
    "            11:'No passing veh over 3.5 tons', \n",
    "            12:'Right-of-way at intersection', \n",
    "            13:'Priority road', \n",
    "            14:'Yield', \n",
    "            15:'Stop', \n",
    "            16:'No vehicles', \n",
    "            17:'Veh > 3.5 tons prohibited', \n",
    "            18:'No entry', \n",
    "            19:'General caution', \n",
    "            20:'Dangerous curve left', \n",
    "            21:'Dangerous curve right', \n",
    "            22:'Double curve', \n",
    "            23:'Bumpy road', \n",
    "            24:'Slippery road', \n",
    "            25:'Road narrows on the right', \n",
    "            26:'Road work', \n",
    "            27:'Traffic signals', \n",
    "            28:'Pedestrians', \n",
    "            29:'Children crossing', \n",
    "            30:'Bicycles crossing', \n",
    "            31:'Beware of ice/snow',\n",
    "            32:'Wild animals crossing', \n",
    "            33:'End speed + passing limits', \n",
    "            34:'Turn right ahead', \n",
    "            35:'Turn left ahead', \n",
    "            36:'Ahead only', \n",
    "            37:'Go straight or right', \n",
    "            38:'Go straight or left', \n",
    "            39:'Keep right', \n",
    "            40:'Keep left', \n",
    "            41:'Roundabout mandatory', \n",
    "            42:'End of no passing', \n",
    "            43:'End no passing veh > 3.5 tons' }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "2a8d9533",
   "metadata": {},
   "outputs": [],
   "source": [
    "window = tk.Tk()\n",
    "window.geometry('1280x853')\n",
    "window.title(\"Traffic Signs Classification\")\n",
    "window.configure(background='#72a31d')\n",
    "\n",
    "label = Label(window, background = '#3f853d', font= ('arial', 20, 'bold'))\n",
    "\n",
    "sign_image = Label(window)\n",
    "\n",
    "\n",
    "# window.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "a484e90e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\Temp\\ipykernel_15048\\2245655422.py\", line 13, in <lambda>\n",
      "    classify_b = Button(window, text=\"Classify Image\", command = lambda: classify(file_path), padx = 12, pady = 9)\n",
      "  File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\Temp\\ipykernel_15048\\2245655422.py\", line 7, in classify\n",
      "    pred = np.argmax(model.predict([image])[0])\n",
      "  File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\MUHAMM~1\\AppData\\Local\\Temp\\__autograph_generated_file2na_1w5n.py\", line 15, in tf__predict_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2341, in predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2327, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2315, in run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2283, in predict_step\n",
      "        return self(x, training=False)\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential\" is incompatible with the layer: expected shape=(None, 43, 43, 3), found shape=(None, 30, 30, 3)\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\Temp\\ipykernel_15048\\2245655422.py\", line 13, in <lambda>\n",
      "    classify_b = Button(window, text=\"Classify Image\", command = lambda: classify(file_path), padx = 12, pady = 9)\n",
      "  File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\Temp\\ipykernel_15048\\2245655422.py\", line 7, in classify\n",
      "    pred = np.argmax(model.predict([image])[0])\n",
      "  File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\MUHAMM~1\\AppData\\Local\\Temp\\__autograph_generated_file2na_1w5n.py\", line 15, in tf__predict_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2341, in predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2327, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2315, in run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 2283, in predict_step\n",
      "        return self(x, training=False)\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"C:\\Users\\Muhammad Talha\\AppData\\Local\\anaconda3\\lib\\site-packages\\keras\\src\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential\" is incompatible with the layer: expected shape=(None, 43, 43, 3), found shape=(None, 30, 30, 3)\n",
      "\n"
     ]
    }
   ],
   "source": [
    "def classify(file_path):\n",
    "    global label_packed\n",
    "    image = Image.open(file_path)\n",
    "    image = image.resize((30,30))\n",
    "    image = np.expand_dims(image, axis=0)\n",
    "    image = np.array(image)\n",
    "    pred = np.argmax(model.predict([image])[0])\n",
    "    sign = classes[pred+1]\n",
    "    print(sign)\n",
    "    label.configure(foreground='#011638', text=sign)\n",
    "    \n",
    "def show_button(file_path):\n",
    "    classify_b = Button(window, text=\"Classify Image\", command = lambda: classify(file_path), padx = 12, pady = 9)\n",
    "    classify_b.configure(background='#364156', foreground='white',font=('arial',10,'bold'))\n",
    "    classify_b.place(relx=0.79,rely=0.46)\n",
    "    \n",
    "    \n",
    "def upload_image():\n",
    "    try:\n",
    "        file_path = filedialog.askopenfilename()\n",
    "        uploaded = Image.open(file_path)\n",
    "        uploaded.thumbnail(((window.winfo_width()/2.25), (window.winfo_height()/2.25)))\n",
    "        im = ImageTk.PhotoImage(uploaded)\n",
    "        \n",
    "        sign_image.configure(image = im)\n",
    "        sign_image.image = im\n",
    "        label.configure(text = '')\n",
    "        show_button(file_path)\n",
    "    except:\n",
    "        pass\n",
    "    \n",
    "upload= Button(window, text = \"Upload an Image\", command = upload_image, padx = 12, pady = 9)\n",
    "upload.configure(background='#364156', foreground='white',font=('arial',10,'bold'))\n",
    "\n",
    "\n",
    "upload.pack(side=BOTTOM, pady=50)\n",
    "sign_image.pack(side = BOTTOM, expand = True)\n",
    "label.pack(side = BOTTOM, expand = True)\n",
    "\n",
    "heading = Label(window, text=\"Know Your Traffic Sign\",pady=20, font=('arial',35,'bold'))\n",
    "heading.configure(background='#72a31d',foreground='#7d3434')\n",
    "\n",
    "heading.pack()\n",
    "# canvas.pack()\n",
    "window.mainloop()\n",
    "    \n",
    "    \n",
    "# window.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5eae0d9f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
